---
argument_specs:
  # ./roles/edpm_iscsid/tasks/main.yml entry point
  main:
    short_description: The main entry point for the edpm_iscsid role.
    options:
      edpm_iscsid_download_delay:
        type: int
        default: 60
        description: The seconds between retries for failed download tasks
      edpm_iscsid_download_retries:
        type: int
        default: 5
        description: The number of retries for failed download tasks
      edpm_iscsid_packages:
        type: list
        description: The list of packages to install for iscsid.
        default:
          - iscsi-initiator-utils
      edpm_iscsid_chap_algs:
        type: str
        default: 'SHA3-256,SHA256,SHA1,MD5'
        description: List of allowed CHAP algorithms.
      edpm_iscsid_legacy_services:
        type: list
        description: |
          The list of legacy containerized services associated with adoption
          and brownfield deployment scenarios.
        default:
          - tripleo_iscsid.service
          - edpm_iscsid.service
      edpm_iscsid_tripleo_config_dir:
        type: str
        default: '/var/lib/config-data/puppet-generated/iscsid/etc/iscsi'
        description: |
          The directory containing the iscsid configuration generated by tripleo.
