---
# Copyright 2022 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Gather ansible_local facts
  ansible.builtin.setup:
    gather_subset:
      - "!all"
      - "!min"
      - "local"
  when:
    - ansible_local is not defined

- name: Clean up legacy containerized iscsid
  ansible.builtin.include_tasks: cleanup_containers.yml

- name: Run iscsid install tasks with root privileges
  become: true
  block:
    - name: Install iscsid packages
      tags:
        - install
        - edpm_iscsid
      ansible.builtin.dnf:
        name: "{{ edpm_iscsid_packages }}"
        state: present
      register: edpm_iscsid_packages_install
      until: edpm_iscsid_packages_install is succeeded
      retries: "{{ edpm_iscsid_download_retries }}"
      delay: "{{ edpm_iscsid_download_delay }}"
      when: ansible_local.bootc is not defined or not ansible_local.bootc

    - name: Detect whether the data plane is being adopted
      ansible.builtin.stat:
        path: "{{ edpm_iscsid_tripleo_config_dir }}"
      register: tripleo_iscsid_config_dir

    - name: Adopt the iscsid configuration
      when:
        - tripleo_iscsid_config_dir.stat.exists
        - tripleo_iscsid_config_dir.stat.isdir
      block:
        - name: Copy the containerized iscsid configuration to the host
          ansible.builtin.copy:
            src: "{{ edpm_iscsid_tripleo_config_dir }}/"
            dest: /etc/iscsi
            remote_src: true
            mode: preserve

        - name: Mark the iscsid adoption complete
          ansible.builtin.command: |
            mv "{{ edpm_iscsid_tripleo_config_dir }}" "{{ edpm_iscsid_tripleo_config_dir }}.adopted"
          changed_when: true

    - name: Check SELinux context of iSCSI directories
      ansible.builtin.command: "/usr/sbin/restorecon -nvr /etc/iscsi /var/lib/iscsi"
      changed_when: false
      register: iscsi_selinux_status

    - name: Restore SELinux context of iSCSI directories
      ansible.builtin.command: "/usr/sbin/restorecon -rF /etc/iscsi /var/lib/iscsi"
      when:
        - iscsi_selinux_status.stdout_lines | length > 0
      changed_when: true
