---
# Copyright 2023 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Prepare
  hosts: all
  gather_facts: false
  roles:
    - role: ../../../../molecule/common/test_deps
    - role: osp.edpm.env_data

- name: Setup DUT
  hosts: all
  gather_facts: false
  vars:
    test_helper_dir: "../../../../molecule/test-helpers"
  tasks:
    - name: Load role vars
      ansible.builtin.include_vars: ../../defaults/main.yml

    - name: Create systemd unit file for mocked legacy containerized services
      become: true
      ansible.builtin.copy:
        dest: "/etc/systemd/system/{{ legacy_service }}"
        content: |
          [Unit]
          Description=Mock containerized iscsid service

          [Service]
          ExecStart=sleep 9999

          [Install]
          WantedBy=multi-user.target
        mode: '0644'
      loop: "{{ edpm_iscsid_legacy_services }}"
      loop_control:
        loop_var: legacy_service

    - name: Enable and start mocked legacy services
      become: true
      ansible.builtin.systemd_service:
        name: "{{ legacy_service }}"
        enabled: true
        state: started
        daemon_reload: true
      loop: "{{ edpm_iscsid_legacy_services }}"
      loop_control:
        loop_var: legacy_service

    - name: Verify mocked legacy services are running
      ansible.builtin.include_tasks: "{{test_helper_dir}}/verify_systemd_unit.yaml"
      vars:
        item:
          name: "{{ legacy_service }}"
      loop: "{{ edpm_iscsid_legacy_services }}"
      loop_control:
        loop_var: legacy_service
