---
# Copyright 2022 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


# All variables intended for modification should be placed in this file.

# All variables within this role should have a prefix of "edpm_iscsid"

# seconds between retries for download tasks
edpm_iscsid_download_delay: "{{ edpm_download_delay | default(60) }}"

# number of retries for download tasks
edpm_iscsid_download_retries: "{{ edpm_download_retries | default(5) }}"

edpm_iscsid_packages:
  - iscsi-initiator-utils

edpm_iscsid_chap_algs: >-
  {{
    'SHA3-256,SHA256' ~
    (edpm_fips_mode |
    default('check', true) == 'enabled') |
    ternary('', ',SHA1,MD5')
  }}

edpm_iscsid_legacy_services:
  - tripleo_iscsid.service
  - edpm_iscsid.service

edpm_iscsid_tripleo_config_dir: '/var/lib/config-data/puppet-generated/iscsid/etc/iscsi'
