---

- name: Configure OvS DPDK
  hosts: "{{ edpm_override_hosts | default('all', true) }}"
  strategy: linear
  gather_facts: "{{ gather_facts | default(false) }}"
  environment: "{{ edpm_playbook_environment | default({}) }}"
  tasks:
    - name: Gather ansible_local facts
      ansible.builtin.setup:
        gather_subset:
          - "!all"
          - "!min"
          - "local"

    - name: Install openvswitch package
      become: true
      ansible.builtin.dnf:
        name: openvswitch
        state: present
      when: ansible_local.bootc is not defined or not ansible_local.bootc

    - name: Configure OvS DPDK configs
      ansible.builtin.import_role:
        name: osp.edpm.edpm_ovs_dpdk
      tags:
        - edpm_ovs_dpdk
