---

- name: Deploy EDPM SSH Known Hosts
  hosts: "{{ edpm_override_hosts | default('all', true) }}"
  strategy: linear
  gather_facts: "{{ gather_facts | default(false) }}"
  any_errors_fatal: "{{ edpm_any_errors_fatal | default(true) }}"
  max_fail_percentage: "{{ edpm_max_fail_percentage | default(0) }}"
  environment: "{{ edpm_playbook_environment | default({}) }}"
  tasks:
    - name: Configure edpm_ssh_known_hosts
      ansible.builtin.import_role:
        name: osp.edpm.edpm_ssh_known_hosts
      tags:
        - edpm_ssh_known_hosts
